FROM python:3.10-slim

WORKDIR /usr/src/app

COPY requirements_jupyter.txt ./
RUN pip install --no-cache-dir -r requirements_jupyter.txt

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
