# version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_pass
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - .:/usr/src/app:rw
      - ./media:/usr/src/app/media
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_pass
      - POSTGRES_HOST=db
    depends_on:
      - db
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  db_data:
